from ADLClassifier.ExtendedClassifier.ADLClassifierWithWinningLayerTraining import ADLClassifierWithWinningLayerTraining
from ADLClassifier.EvaluationClassifier.EvaluationWrapper import record_emissions, record_network_graph


@record_network_graph
class WinningLayerADLClassifierWithGraphRecord(ADLClassifierWithWinningLayerTraining):
    pass


@record_emissions
@record_network_graph
class WinningLayerADLClassifierWithGraphRecordAndEmissionTracking(ADLClassifierWithWinningLayerTraining):
    pass
