from ADLClassifier.ExtendedClassifier.FunctionalityWrapper.GracePeriod.global_grace_period import global_grace_period, GLOBAL_GRACE_PERIOD_NAME
from ADLClassifier.ExtendedClassifier.FunctionalityWrapper.GracePeriod.grace_period_per_layer import grace_period_per_layer, GRACE_PERIOD_PER_LAYER_NAME
